---
- name: download and install all the gui apps you need via homebrew casks
  hosts: localhost
  vars:
    apps:
      - 1password
      - amazon-workspaces
      - firefox
      - intellij-idea-ce
      - iterm2
      - github
      - google-chrome
      - pycharm-ce
      - slack
      - zoom
  tasks:
    - name: loop through apps installed via cask
      homebrew_cask:
        name: "{{ item }}"
      loop: "{{ apps }}"
- name: download and install all the apps you need via homebrew
  hosts: localhost
  vars:
    apps:
      - bat
      - cowsay
      - tree
  tasks:
    - name: loop through apps installed via cask
      homebrew:
        name: "{{ item }}"
      loop: "{{ apps }}"
