---
- name: downloading and installing all the apps you need
  hosts: localhost
  vars:
    apps:
      - 1password
      - amazon-workspaces
      - firefox
      - intellij-idea-ce
      - iterm2
      - github
      - google-chrome
      - pycharm-ce
      - slack
      - zoom
  tasks:
    - name: looping through app installs
      homebrew_cask:
        name: "{{ item }}"
      loop: "{{ apps }}"
