---
- name: main
  hosts: localhost
  tasks:
    - import_tasks: configure_os.yml
    - import_tasks: configure_hostname.yml

- name: download and install all the gui apps you need via homebrew casks
  hosts: localhost
  vars:
    apps:
      - 1password
      - amazon-workspaces
      - firefox
      - intellij-idea-ce
      - iterm2
      - github
      - google-chrome
      - parallels
      - pycharm-ce
      - slack
      - zoom
  tasks:
    - import_tasks: update_homebrew.yml
    - name: loop through apps installed via cask
      homebrew_cask:
        name: "{{ item }}"
      loop: "{{ apps }}"

- name: download and install all the apps you need via homebrew
  hosts: localhost
  vars:
    apps:
      - awscli
      - bat
      - cli53
      - cowsay
      - tree
  tasks:
    - name: loop through apps installed via homebrew
      homebrew:
        name: "{{ item }}"
      loop: "{{ apps }}"

- name: remove everything from the dock
  hosts: localhost
  tasks:
    - import_tasks: remove_all_items_from_dock.yml

- name: populate the dock with apps you use most often
  hosts: localhost
  vars:
    apps:
      - '/Applications/1Password.app'
      - '/Applications/Atom.app'
      - '/System/Applications/Books.app'
      - '/Applications/Firefox.app'
      - '/Applications/Github Desktop.app'
      - '/Applications/Google Chrome.app'
      - '/Applications/IntelliJ IDEA CE.app'
      - '/Applications/iTerm.app'
      - '/Applications/Logic Pro X.app'
      - '/System/Applications/Music.app'
      - '/Applications/Parallels Desktop.app'
      - '/Applications/Pluralsight.app'
      - '/System/Applications/Podcasts.app'
      - '/Applications/Postman.app'
      - '/Applications/PyCharm CE.app'
      - '/Applications/Safari.app'
      - '/Applications/Slack.app'
      - '/Applications/WorkSpaces.app'
      - '/Applications/zoom.us.app'
  tasks:
    - name: adding 1Password, Atom, Firefox, etc. to the dock
      command:
        dockutil --add '{{ item }}'
      loop: "{{ apps }}"

- name: arranging apps in the dock in the order you like
  hosts: localhost
  vars:
    dockitems_to_persist:
      - name: Books
        pos: 1
      - name: 1Password
        pos: 2
      - name: Parallels Desktop
        pos: 3
      - name: Atom
        pos: 4
      - name: IntelliJ IDEA CE
        pos: 5
      - name: PyCharm CE
        pos: 6
      - name: iTerm
        pos: 7
      - name: Postman
        pos: 8
      - name: Github Desktop
        pos: 9
      - name: Firefox
        pos: 10
      - name: Safari
        pos: 11
      - name: Google Chrome
        pos: 12
      - name: WorkSpaces
        pos: 13
      - name: Pluralsight
        pos: 14
      - name: Slack
        pos: 15
      - name: zoom.us
        pos: 16
      - name: Logic Pro X
        pos: 17
      - name: Music
        pos: 18
      - name: Podcasts
        pos: 19
  tasks:
    - name: Books, 1Password, software development apps, browsers, communication, entertainment
      command:
        dockutil --move '{{ item.name }}' --position {{ item.pos }}
      loop: "{{ dockitems_to_persist }}"
