---
- name: Fix order
  hosts: localhost
  vars:
    dockitems_to_persist:
      - name: Atom
        pos: 1
      - name: IntelliJ IDEA CE
        pos: 2
      - name: PyCharm CE
        pos: 3
      - name: iTerm
        pos: 4
      - name: Firefox
        pos: 5
      - name: Safari
        pos: 6
      - name: Google Chrome
        pos: 7
      - name: WorkSpaces
        pos: 8
      - name: Pluralsight
        pos: 9
      - name: Logic Pro X
        pos: 10
      - name: Music
        pos: 11
      - name: Podcasts
        pos: 12
  tasks:
    - name: order apps in the doc
      command:
        dockutil --move '{{ item.name }}' --position {{ item.pos }}
      loop: "{{ dockitems_to_persist }}"
