---
- name: arranging apps in the dock in the order you like
  hosts: localhost
  vars:
    dockitems_to_persist:
      - name: 1Password
        pos: 1
      - name: Atom
        pos: 2
      - name: IntelliJ IDEA CE
        pos: 3
      - name: PyCharm CE
        pos: 4
      - name: iTerm
        pos: 5
      - name: Postman
        pos: 6
      - name: Github Desktop
        pos: 7
      - name: Firefox
        pos: 8
      - name: Safari
        pos: 9
      - name: Google Chrome
        pos: 10
      - name: WorkSpaces
        pos: 11
      - name: Pluralsight
        pos: 12
      - name: Slack
        pos: 13
      - name: zoom.us
        pos: 14
      - name: Logic Pro X
        pos: 15
      - name: Music
        pos: 16
      - name: Podcasts
        pos: 17
  tasks:
    - name: 1Password, software development apps, browsers, communication, entertainment
      command:
        dockutil --move '{{ item.name }}' --position {{ item.pos }}
      loop: "{{ dockitems_to_persist }}"
