---
- name: populate dock
  hosts: localhost
  vars:
    apps:
      - '/Applications/Atom.app'
      - '/Applications/Firefox.app'
      - '/Applications/Github Desktop.app'
      - '/Applications/Google Chrome.app'
      - '/Applications/IntelliJ IDEA CE.app'
      - '/Applications/iTerm.app'
      - '/System/Applications/Music.app'
      - '/System/Applications/Podcasts.app'
      - '/Applications/Safari.app'
      - '/Applications/WorkSpaces.app'
  tasks:
    - name: order items
      command:
        dockutil --add '{{ item }}'
      loop: "{{ apps }}"
