---
- name: order items in the dock
  hosts: localhost
  vars:
    apps:
      - '/Applications/Atom.app'
      - '/Applications/Firefox.app'
      - '/Applications/Google Chrome.app'
      - '/Applications/IntelliJ IDEA CE.app'
      - '/Applications/iTerm.app'
      - '/Applications/Logic Pro X.app'
      - '/System/Applications/Music.app'
      - '/System/Applications/Podcasts.app'
      - '/Applications/Pluralsight.app'
      - '/Applications/PyCharm CE.app'
      - '/Applications/Safari.app'
      - '/Applications/WorkSpaces.app'
  tasks:
    - name: add apps to the dock
      command:
        dockutil --add '{{ item }}'
      loop: "{{ apps }}"
